version: '2'
services:
    zk1:
        image: zookeeper
        container_name: zk1
        networks:
            - zknet
        restart: always
        ports:
            - 21811:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888

    zk2:
        image: zookeeper
        container_name: zk2
        networks:
            - zknet
        restart: always
        ports:
            - 21812:2181
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888

    zk3:
        image: zookeeper
        container_name: zk3
        networks:
            - zknet
        restart: always
        ports:
            - 21813:2181
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888

networks:
    zknet: