version: '2'
services:
    zk1:
      extends:
        file: common.yml
        service: zookeeper
      container_name: zk1
      volumes:
        - ./1/data:/data
        - ./1/logs:/datalog
        - ./conf/zoo.cfg:/conf/zoo.cfg
      ports:
        - "2181:2181"

    zk2:
      extends:
        file: common.yml
        service: zookeeper
      container_name: zk2
      volumes:
        - ./2/data:/data
        - ./2/logs:/datalog
        - ./conf/zoo.cfg:/conf/zoo.cfg
      ports:
        - "2182:2181"

    zk3:
      extends:
        file: common.yml
        service: zookeeper
      container_name: zk3
      volumes:
        - ./3/data:/data
        - ./3/logs:/datalog
        - ./conf/zoo.cfg:/conf/zoo.cfg
      ports:
        - "2183:2181"

    zkui:
        image: maauso/zkui
        container_name: zkui
        networks:
            - zoo
        ports:
            - "9090:9090"
        environment:
            ZKLIST: zk1:2181,zk2:2181,zk3:2181
        links:
            - zk1:zk1
            - zk2:zk2
            - zk3:zk3
networks:
    zoo:
      driver: bridge